- build.gradle
- src/main/resources/application.yaml
- main 실행시에는 `MySql` 사용
- test 실행시에는 `H2` 사용
추후에 docker를 사용해보자
Closes #4
> [Feat] Yaml 설정하기

- src/main/java/cotato/bookitlist/global/controller/GlobalController.java
HTTPS 설정 중 ELB 대상 그룹 등록을 위한 health check API 구현
- Global Controller 만들어서 "/health_check" endpoint에 간단하게 200 응답만 하는 API 구현
Closes #7
> [Feat] health check API 구현

- build.gradle
- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
> [Feat] Swagger 설정 추가하기

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
- src/main/java/cotato/bookitlist/book/dto/BookDto.java
- src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookResponse.java
- src/main/java/cotato/bookitlist/book/repository/BookRepository.java
- src/main/java/cotato/bookitlist/book/service/BookApiComponent.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- 조회 api 구현
단순 코드리팩토링 
List<BookApiDto> bookApiDto -> List<BookApiDto> bookApiDtoList
from -> of
Closes #20
> [Feat] DB에서 책 조회 api 구현

- build.gradle
- src/main/java/cotato/bookitlist/config/P6SpyConfig.java
- src/main/java/cotato/bookitlist/config/P6SpyEventListener.java
- src/main/java/cotato/bookitlist/config/P6SpyFormatter.java
- src/main/resources/application.yaml
- `p6spy` 설정 추가
기존의 hibernate 로그 끔
Closes #22
> [Feat] sql로그를 예쁘게 보기위해 p6spy 도입

- .github/workflows/deploy.yaml
- 설정값 외부 주입을 위한 deploy.yaml 파일 수정
Closes #26
> [Feat] 설정값 외부 주입을 위한 deploy.yaml 파일 수정

- .github/workflows/deploy.yaml
- 설정값 외부 주입을 위한 deploy.yaml 파일 재수정
Closes #30
> [Feat] 설정값 외부 주입을 위한 deploy.yaml 파일 재수정

- src/main/java/cotato/bookitlist/config/SwaggerConfig.java
- 로컬과 배포 환경에 따른 Swagger 설정
- Swagger에서의 Authorization 설정
Closes #32
> [Feat] 로컬과 배포 환경에 따른 Swagger 설정, Swagger에서의 Authorization 설정

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/domain/entity/Book.java
- src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
- src/main/java/cotato/bookitlist/book/dto/request/BookRegisterRequest.java
- src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookResponse.java
- src/main/java/cotato/bookitlist/book/repository/BookRepository.java
- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- src/main/java/cotato/bookitlist/member/domain/Member.java
- src/main/java/cotato/bookitlist/post/domain/Post.java
- src/main/java/cotato/bookitlist/review/domain/Review.java
- cover500sum 으로 나오는 부분을 cover500으로 나올 수 있게 수정
- api의 key에 dto 로 된 부분 변경
- `swagger` 에 안나와도 되는 부분 숨김
Closes #34
> [Feat] 책 검색 기능 수정

- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- #34 수정 후 실패한 테스트 해결
Closes #36
> [Feat] 배포중 테스트 실패 해결

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/controller/IsValidIsbn.java
- src/main/java/cotato/bookitlist/book/controller/IsbnValidator.java
- src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
- src/main/java/cotato/bookitlist/book/dto/BookDto.java
- src/main/java/cotato/bookitlist/book/dto/request/BookRegisterRequest.java
- src/main/java/cotato/bookitlist/book/dto/response/BookApiListResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookListResponse.java
- src/main/java/cotato/bookitlist/book/service/BookApiComponent.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- 검색과 상세 조회 api endpoint 분리
- @IsValidIsbn 생성
Closes #38
> [Feat] 외부 api 요청에서 검색과 상세 조회 api 분리하기

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/dto/BookDto.java
- src/main/java/cotato/bookitlist/book/dto/response/BookResponse.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- id 를 이용하여 책 상세조회 기능 구현
`EntityNotFoundException` 예외시 404 응답을 주게함
Closes #42
> [Feat] DB에 저장되어 있는 책 상세 조회 api 구현

- src/main/java/cotato/bookitlist/config/security/jwt/AuthDetails.java
- 커스텀 로그인 객체를 받을 수 있도록 메소드 추가
Closes #45
> [Feat] 커스텀 로그인 객체 처리 부분 리팩토링

- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/domain/Post.java
- src/main/java/cotato/bookitlist/post/dto/PostUpdateRequest.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/resources/data.sql
- 게시글 수정 api 구현
- 게시글 수정 테스트 구현
Closes #48
> [Feat] 게시글 수정 api 구현

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/domain/Review.java
- src/main/java/cotato/bookitlist/review/dto/request/ReviewUpdateRequest.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/resources/data.sql
- 한줄요약 수정 API 구현
- 한줄요약 수정 API 테스트 코드 구현
- 멤버 컬럼 이름 잘못된 부분 변경
Closes #50
> [Feat] 한줄요약 수정 API 구현

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- 커밋하지 않아야 할 코드 커밋한 오류 수정
Closes #55
> [Fix] 빌드 오류 수정

- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/dto/PostDto.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostRegisterRequest.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostUpdateRequest.java
- src/main/java/cotato/bookitlist/post/dto/response/PostResponse.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- 게시글 id로 게시글 조회 기능 구현
- 테스트 코드 구현
Closes #54
> [Feat] 게시글 조회 api 구현

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/dto/ReviewDto.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewResponse.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- 한줄요약 조회 API 구현
- 한줄요약 조회 API 테스트 구현
@Valid 중복 검사한 부분 삭제
Closes #58
> [Feat] 한줄요약 조회 API 구현

- src/main/java/cotato/bookitlist/book/dto/response/BookListResponse.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/dto/response/PostListResponse.java
- src/main/java/cotato/bookitlist/post/repository/PostRepository.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/resources/data.sql
- isbn13을 활용하여 게시글 조회 api를 구현함
- isbn13이 없는 경우에는 모든 게시글 조회 api 구현
Closes #61
> [Feat] 게시글 리스트 조회 기능을 구현한다.

- src/main/java/cotato/bookitlist/post/controller/PostLikeController.java
- src/main/java/cotato/bookitlist/post/domain/Post.java
- src/main/java/cotato/bookitlist/post/domain/PostLike.java
- src/main/java/cotato/bookitlist/post/repository/PostLikeRepository.java
- src/main/java/cotato/bookitlist/post/service/PostLikeService.java
- src/test/java/cotato/bookitlist/post/controller/PostLikeControllerTest.java
- src/test/java/cotato/bookitlist/post/service/PostLikeServiceTest.java
- 게시글 좋아요 기능 구현함
- 게시글 좋아요시 Post Entity 의 LikeCount 도 증가해야 되기 때문에 Service Test 도 구현하여 확인
Closes #65
> [Feat] 게시글 좋아요 기능 구현

- src/main/java/cotato/bookitlist/post/controller/PostLikeController.java
- src/main/java/cotato/bookitlist/post/domain/Post.java
- src/main/java/cotato/bookitlist/post/domain/PostLike.java
- src/main/java/cotato/bookitlist/post/service/PostLikeService.java
- src/test/java/cotato/bookitlist/post/controller/PostLikeControllerTest.java
- src/test/java/cotato/bookitlist/post/service/PostLikeServiceTest.java
- src/test/resources/data.sql
- 게시글 좋아요 삭제 api 구현
- 구현한 api 테스트 코드 작성
Closes #67
> [Feat] 게시글 좋아요 취소 기능 구현

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewCountResponse.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewListResponse.java
- src/main/java/cotato/bookitlist/review/repository/ReviewRepository.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/resources/data.sql
- isbn13 을 활용하여 해당 책의 한줄요약 리스트 조회 구현. 또한 한줄요약 리스트 조회 구현
- 책과 관련된 한줄요약 수 가져오는 기능 구현
- 전체 한줄요약, 해당 책의 한줄요약, 책의 한줄요약 개수 조회하는 테스트 코드 구현
Closes #71
> [Feat] 한줄요약 리스트 조회 API 구현

- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/dto/PostDetailDto.java
- src/main/java/cotato/bookitlist/post/dto/response/PostResponse.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustom.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- 게시글 상세 조회 시 디테일한 정보를 추가한다.
- 관련된 기능 테스트 작성
Closes #74
> [Feat] 게시글 상세 조회시 생성일자 작성자 등의 추가 정보를 보내주는 기능 구현

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/dto/response/BookApiListResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
- src/main/java/cotato/bookitlist/book/service/BookApiComponent.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- 기존 외부 검색 API를 검색 API로 전환하고 기존 검색 API는 Deprecated 처리
Closes #60
> [Feat] 책 검색시 DB 검색을 제외하고 알라딘 api 활용으로 대체하기

- src/main/java/cotato/bookitlist/post/dto/requeset/PostRegisterRequest.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/main/java/cotato/bookitlist/review/dto/request/ReviewRegisterRequest.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- 게시글, 한줄요약 등록을 book id 가 아닌 isbn13으로 받도록 변경
- 게시글, 한줄요약 등록 시 해당 책이 등록됐는지 검사
- 등록되지 않았을 경우 책을 자동등록 후 등록할 게시글, 한줄요약 등록
Closes #78
> [Feat] 게시글, 한줄요약 등록 시 해당 책이 등록됐는지 검사 후 자동등록

- .github/workflows/deploy.yaml
- src/main/resources/application.yaml
- 데이터베이스의 ddl-auto 를 외부에서 주입하도록 변경
Closes #80
> [Feat] 데이터베이스의 ddl-auto 를 외부에서 주입하도록 변경

- .github/workflows/deploy.yaml
- build.gradle
- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- src/main/java/cotato/bookitlist/config/AwsS3Config.java
- src/main/java/cotato/bookitlist/config/p6spy/P6SpyConfig.java
- src/main/java/cotato/bookitlist/config/p6spy/P6SpyEventListener.java
- src/main/java/cotato/bookitlist/config/p6spy/P6SpyFormatter.java
- src/main/java/cotato/bookitlist/file/service/FileService.java
- src/main/java/cotato/bookitlist/member/controller/MemberController.java
- src/main/java/cotato/bookitlist/member/domain/Member.java
- src/main/java/cotato/bookitlist/member/dto/ProfileResponse.java
- src/main/java/cotato/bookitlist/member/service/MemberService.java
- src/main/resources/application.yaml
- S3 설정 추가
- S3에 파일 업로드 기능 구현
- member profile 업로드 로직 구현
직접적으로 S3와 통신을 하기 때문에 테스트 코드 방식 고민후 추후 작성
Closes #83
> [Feat] S3를 활용하여 파일 업로드 기능 구현

- .github/workflows/deploy.yaml
- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- 테스트 실패 해결
RunTimeExceptionHandler를 등록하면 왜 다른 메시지로 응답을 주는지 알아봐야함
Closes #90
> [Fix] CI/CD 배포 실패 해결하기

- src/main/java/cotato/bookitlist/book/controller/BookLikeController.java
- src/main/java/cotato/bookitlist/book/domain/entity/Book.java
- src/main/java/cotato/bookitlist/book/domain/entity/BookLike.java
- src/main/java/cotato/bookitlist/book/repository/BookLikeRepository.java
- src/main/java/cotato/bookitlist/book/service/BookLikeService.java
- src/test/java/cotato/bookitlist/book/controller/BookLikeControllerTest.java
- src/test/java/cotato/bookitlist/book/service/BookLikeServiceTest.java
- src/test/resources/data.sql
- 도서 좋아요 취소 api 구현
- 구현한 api 테스트 코드 작성
도서 좋아요 등록시 이미 좋아요 정보가 존재하는지 확인 로직 추가
Closes #97
> [Feat] 도서 좋아요 취소 api 구현

- src/test/java/cotato/bookitlist/post/controller/PostLikeControllerTest.java
- 게시글 좋아요 기능 테스트 수정
Closes #99
> [Feat] 게시글 좋아요 등록시 이미 좋아요 정보가 존재하는지 확인 로직 추가

- src/main/java/cotato/bookitlist/post/domain/PostStatus.java
- src/main/java/cotato/bookitlist/post/domain/entity/Post.java
- src/main/java/cotato/bookitlist/post/domain/entity/PostLike.java
- src/main/java/cotato/bookitlist/post/dto/PostDto.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostRegisterRequest.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostUpdateRequest.java
- src/main/java/cotato/bookitlist/post/dto/response/PostListResponse.java
- src/main/java/cotato/bookitlist/post/repository/PostLikeRepository.java
- src/main/java/cotato/bookitlist/post/repository/PostRepository.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustom.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostLikeService.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/post/service/PostLikeServiceTest.java
- src/test/java/cotato/bookitlist/post/service/PostServiceTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/resources/data.sql
- 게시글 공개, 비공개 기능 구현
- PostStaus Enun을 이용해 공개, 비공개 여부 확인
- 조회 시 public 게시글만 조회할 수 있도록 method 수정
리뷰 테스트 잘못된 부분 수정
Closes #101
> [Feat] 게시글 공개 비공개 설정 추가하기

- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/domain/Review.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- 한줄요약 조회수 기능 구현
- 한줄요약 조회수 기능 테스트 구현
Closes #107
> [Feat] 한줄요약 조회수 기능 구현

- src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/domain/PostTemplate.java
- src/main/java/cotato/bookitlist/post/domain/entity/Post.java
- src/main/java/cotato/bookitlist/post/dto/PostDetailDto.java
- src/main/java/cotato/bookitlist/post/dto/PostDto.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostRegisterRequest.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostUpdateRequest.java
- src/main/java/cotato/bookitlist/post/dto/response/PostDetailResponse.java
- src/main/java/cotato/bookitlist/post/dto/response/PostListResponse.java
- src/main/java/cotato/bookitlist/post/dto/response/PostResponse.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/post/service/PostLikeServiceTest.java
- src/test/java/cotato/bookitlist/post/service/PostServiceTest.java
- src/test/resources/data.sql
- 게시글 템플릿 기능을 구현함
- DB 에서는 String 형식으로 가져오고 이후 Response 로 변환하는 과정에서 문자열 처리함
- 구현한 기능 테스트 코드 작성
Closes #104
> [Feat] 게시글 템플릿 기능 구현하기

- src/main/java/cotato/bookitlist/config/WebConfig.java
CORS 설정
- 프론트엔드의 로컬, 배포 주소에 CORS 해제
Closes #113
> [Feat] CORS 설정

- src/test/java/cotato/bookitlist/book/service/BookLikeServiceTest.java
- src/test/java/cotato/bookitlist/fixture/BookFixture.java
- src/test/java/cotato/bookitlist/fixture/BookLikeFixture.java
- src/test/java/cotato/bookitlist/fixture/MemberFixture.java
- src/test/java/cotato/bookitlist/fixture/PostFixture.java
- src/test/java/cotato/bookitlist/fixture/PostLikeFixture.java
- src/test/java/cotato/bookitlist/fixture/ReviewFixture.java
- src/test/java/cotato/bookitlist/fixture/ReviewLikeFixture.java
- src/test/java/cotato/bookitlist/post/service/PostLikeServiceTest.java
- src/test/java/cotato/bookitlist/post/service/PostServiceTest.java
- src/test/java/cotato/bookitlist/review/service/ReviewLikeServiceTest.java
- src/test/java/cotato/bookitlist/review/service/ReviewServiceTest.java
- fixture를 이용하여 퍼져있는 create 문을 합침
Closes #119
> [Feat] 테스트에 퍼져있는 create 문 Fixture로 모으기

- src/main/java/cotato/bookitlist/auth/service/AuthService.java
- src/main/java/cotato/bookitlist/config/security/jwt/JwtAuthenticationFilter.java
- src/main/java/cotato/bookitlist/config/security/jwt/JwtTokenProvider.java
- 토큰 검증 시 회원가입된 유저인지 검사
- JWT 관련 예외처리 수정
Closes #105
> [Feat] Access Token 검사 시 DB를 검사하지 않는 오류 수정

- src/main/java/cotato/bookitlist/member/controller/MemberController.java
- src/main/java/cotato/bookitlist/member/domain/Member.java
- src/main/java/cotato/bookitlist/member/service/MemberService.java
- src/main/java/cotato/bookitlist/post/repository/PostRepository.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/test/java/cotato/bookitlist/member/controller/MemberControllerTest.java
- src/test/java/cotato/bookitlist/member/service/MemberServiceTest.java
- src/test/resources/data.sql
- 멤버의 프로필 상태에 따라 게시글 공개 여부 기능 구현
- 구현한 기능 테스트 작성
멤버 프로필 상태 변경 api 구현
Closes #122
> [Feat] 유저 프로필 비공개 시 게시물도 비공개 상태로 하는 기능 구현

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/domain/entity/Review.java
- src/main/java/cotato/bookitlist/review/repository/ReviewLikeRepository.java
- src/main/java/cotato/bookitlist/review/repository/ReviewRepository.java
- src/main/java/cotato/bookitlist/review/service/ReviewFacade.java
- src/main/java/cotato/bookitlist/review/service/ReviewLikeService.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/resources/data.sql
- 한줄요약 삭제 API 구현
- 한줄요약 삭제 API 테스트 구현
Closes #126
> [Feat] 한줄요약 삭제 API 구현

- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- 단순 숫자 오류로 인한 테스트 실패 해결
Closes #129
> [Feat] 한줄요약 테스트 실패 오류 해결

- src/main/java/cotato/bookitlist/auth/service/AuthService.java
- 멤버를 데이터베이스에서 가져오는 부분에서 ! 연산자가 누락된 것을 해결
Closes #133
> [Fix] Access Token 검증 오류 해결

- src/main/java/cotato/bookitlist/book/annotation/IsbnValidator.java
- src/main/java/cotato/bookitlist/book/dto/request/BookIsbn13Request.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostRegisterRequest.java
- src/main/java/cotato/bookitlist/post/dto/requeset/PostUpdateRequest.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustom.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- 유저가 작성한 게시글 조회 api 구현
- 구현한 기능 테스트 작성
Closes #132
> [Feat] 멤버가 작성한 게시글 조회 api 구현하기

- src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustom.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/resources/data.sql
- 좋아요한 게시글 조회 기능 구현
- 좋아요한 게시글 조회 테스트 작성
Closes #136
> [Feat] 좋아요한 게시글 조회 api 구현

- src/main/java/cotato/bookitlist/post/domain/entity/Post.java
- src/main/java/cotato/bookitlist/post/service/PostLikeService.java
- src/test/java/cotato/bookitlist/post/controller/PostLikeControllerTest.java
- src/test/java/cotato/bookitlist/post/service/PostLikeServiceTest.java
- 본인 게시글 좋아요 불가 기능 구현
- 구현한 기능 테스트 작성
Closes #138
> [Feat] 본인이 작성한 게시글에는 좋아요 못하게 하는 기능 구현

- src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/dto/PostDetailDto.java
- src/main/java/cotato/bookitlist/post/dto/PostDto.java
- src/main/java/cotato/bookitlist/post/dto/response/PostDetailResponse.java
- src/main/java/cotato/bookitlist/post/dto/response/PostResponse.java
- src/main/java/cotato/bookitlist/post/repository/PostRepository.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/post/controller/PostLikeControllerTest.java
- 본인 게시글 조회 기능 구현
- 게시글 리스트 조회시 PostStatus도 같이 보내줌
Closes #140
> [Feat] 내 게시글 조회 api 구현

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/repository/BookRepository.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- 내가 찜한 책 조회 기능 구현
`@Query`에서 소문자를 이용해 jpql 표현
Closes #142
> [Feat] 내가 찜한 책 조회 기능 구현

- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustom.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- private 게시글 상세 조회 기능 구현
- private 게시글 접근 가능 여부를 레포에서 만들어 주고 있음
Closes #144
> [Feat] private 게시글 상세조회 기능 구현

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/controller/BookLikeController.java
- src/main/java/cotato/bookitlist/book/domain/Book.java
- src/main/java/cotato/bookitlist/book/domain/BookLike.java
- src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
- src/main/java/cotato/bookitlist/book/dto/BookDto.java
- src/main/java/cotato/bookitlist/book/dto/response/BookLikeResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookListResponse.java
- src/main/java/cotato/bookitlist/book/redis/BookApiCache.java
- src/main/java/cotato/bookitlist/book/repository/BookApiCacheRepository.java
- src/main/java/cotato/bookitlist/book/repository/BookLikeRepository.java
- src/main/java/cotato/bookitlist/book/repository/BookRepository.java
- src/main/java/cotato/bookitlist/book/service/BookApiCacheService.java
- src/main/java/cotato/bookitlist/book/service/BookLikeService.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
- src/main/java/cotato/bookitlist/mark/domain/ReadBook.java
- src/main/java/cotato/bookitlist/post/domain/entity/Post.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/main/java/cotato/bookitlist/review/domain/entity/Review.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- src/test/java/cotato/bookitlist/book/controller/BookLikeControllerTest.java
- src/test/java/cotato/bookitlist/book/service/BookLikeServiceTest.java
- src/test/java/cotato/bookitlist/fixture/BookFixture.java
- src/test/java/cotato/bookitlist/fixture/BookLikeFixture.java
- 책 좋아요 했는지 확인 기능 구현
- like 관련 정보는 like controller에서 처리하게 함
domain 패키지와 dto 패키지의 순환참조를 해결하기 위해 redis 패키지 분리
Closes #148
> [Feat] 책을 좋아요 했는지 확인 기능 구현 

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/dto/ReviewDetailDto.java
- src/main/java/cotato/bookitlist/review/dto/ReviewDto.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewDetailResponse.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewListResponse.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewResponse.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- 기존에 한줄요약 응답을 목록 응답과 같은 정보로 간략하게 응답하고 있던 부분을 자세하게 응답하기 위해 ReviewDetailDto 를 추가하고 로직도 수정
Closes #143
> [Feat] 한줄요약 리스트 응답 시 자세한 정보가 아닌 간략한 정보를 응답하는 부분 수정

- src/main/java/cotato/bookitlist/book/controller/BookController.java
- src/main/java/cotato/bookitlist/book/dto/response/BookRecommendListResponse.java
- src/main/java/cotato/bookitlist/book/dto/response/BookRecommendResponse.java
- src/main/java/cotato/bookitlist/book/repository/BookRepository.java
- src/main/java/cotato/bookitlist/book/service/BookService.java
- src/main/java/cotato/bookitlist/common/domain/RecommendType.java
- src/main/java/cotato/bookitlist/member/controller/MemberController.java
- src/main/java/cotato/bookitlist/member/domain/Member.java
- src/main/java/cotato/bookitlist/member/dto/MemberDto.java
- src/main/java/cotato/bookitlist/member/dto/response/MemberRecommendListResponse.java
- src/main/java/cotato/bookitlist/member/dto/response/MemberRecommendResponse.java
- src/main/java/cotato/bookitlist/member/repository/MemberRepository.java
- src/main/java/cotato/bookitlist/member/service/MemberService.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/repository/PostRepository.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/main/resources/application.yaml
- src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
- src/test/java/cotato/bookitlist/member/controller/MemberControllerTest.java
- src/test/java/cotato/bookitlist/member/service/MemberServiceTest.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/resources/data.sql
- 홈 화면 상단 책 랜덤 추천 API 구현
- 홈 화면 중단 좋아요 순서 게시글 API 구현
- 홈 화면 중단 최신 순서 게시글 API 구현
- 홈 화면 중단 좋아요 순서 한줄요약 API 구현
- 홈 화면 중단 최신 순서 한줄요약 API 구현
- 홈 화면 하단 새로운 기록가들 API 구현
멤버의 profileStatus 변수명을 status 로 변경
Closes #131
> [Feat] 홈 화면과 관련된 API 구현

- src/main/java/cotato/bookitlist/config/WebConfig.java
- src/main/java/cotato/bookitlist/member/controller/MemberController.java
- API 설계를 /recommend/new 에서 /recommend 로 수정
cors 허용 주소에 포트 번호 3000 추가
Closes #158
> [Feat] 홈화면 하단 기록가 추천 API 설계 변경

- src/test/java/cotato/bookitlist/member/controller/MemberControllerTest.java
- 바뀐 API 설계에 따라 테스트 변경
Closes #158
> [Feat] 홈화면 하단 기록가 추천 API 설계 변경에 따라 테스트 변경

- src/main/java/cotato/bookitlist/book/domain/BookLike.java
- src/main/java/cotato/bookitlist/book/repository/BookRepository.java
- src/main/java/cotato/bookitlist/post/domain/entity/PostLike.java
- src/main/java/cotato/bookitlist/post/repository/querydsl/PostRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/review/domain/entity/ReviewLike.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustomImpl.java
- src/test/java/cotato/bookitlist/book/controller/BookLikeControllerTest.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/resources/data.sql
- 좋아요한 정보들 요청시 정렬기능 추가
정렬을 하기 위해 BaseEntity를 추가함
Closes #153
> [Feat] querydsl 사용 쿼리 정렬 기능 추가

- src/main/java/cotato/bookitlist/member/dto/MemberDto.java
- src/main/java/cotato/bookitlist/member/dto/response/MemberResponse.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustom.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- 멤버가 작성한 한줄요약 조회 API 구현
- 멤버가 작성한 한줄요약 조회 API 테스트 구현
Closes #155
> [Feat] 멤버가 작성한 한줄요약 조회 API 구현

- src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/domain/entity/Review.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustom.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/review/service/ReviewLikeService.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewLikeControllerTest.java
- src/test/java/cotato/bookitlist/review/service/ReviewLikeServiceTest.java
- 내가 좋아요한 한줄요약 조회 API 구현
- 내가 좋아요한 한줄요약 조회 API 테스트 구현
- 본인의 한줄요약에는 좋아요 할 수 없는 기능 추가
Closes #166
> [Feat] 내가 좋아요한 한줄요약 조회 API 구현

- src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
- src/main/java/cotato/bookitlist/member/controller/MemberController.java
- src/test/java/cotato/bookitlist/member/controller/MemberControllerTest.java
> [Feat] 본인의 정보를 조회하는 api 구현

- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/repository/ReviewRepository.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- 내가 쓴 한줄요약 조회 API 구현
- 내가 쓴 한줄요약 조회 API 테스트 구현
Closes #164
> [Feat] 내가 쓴 한줄요약 API 구현

- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustom.java
- src/main/java/cotato/bookitlist/review/repository/querydsl/ReviewRepositoryCustomImpl.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/resources/data.sql
- private 한줄요약 상세조회 API 테스트 구현
private 게시글도 찾을 수 있는 메소드에 public 이 들어간 메소드명 변경
Closes #165
> [Feat] private 한줄요약 상세조회 API 테스트 구현

- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/domain/entity/Post.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/domain/entity/Review.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- src/test/java/cotato/bookitlist/fixture/ReviewFixture.java
- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/post/service/PostServiceTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- src/test/java/cotato/bookitlist/review/service/ReviewServiceTest.java
- 게시글, 한줄요약 상태 변경 api 구현
Closes #177
> [Feat] 게시글, 한줄요약 status 변경 api 구현

- src/main/java/cotato/bookitlist/post/dto/response/PostDetailResponse.java
- src/main/java/cotato/bookitlist/post/dto/response/PostResponse.java
- src/main/java/cotato/bookitlist/review/dto/response/ReviewDetailResponse.java
- postStatus 응답 변수을 status 로 바꿈
- reviewStatus 응답 변수을 status 로 바꿈
Closes #176
> [Feat] status 응답 변수명 통일

- src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
- src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
- status 응답 변수명 변경으로 인한 테스트 오류 해결
Closes #182
> [Fix] status 응답 변수명 변경으로 인한 테스트 오류 해결

- .github/workflows/deploy.yaml
- src/main/resources/application-oauth.yaml
- JWT 발급 리다이렉트 URI 를 외부 주입으로 변경
Closes #180
> [Feat] JWT 발급 리다이렉트 URI 를 외부 주입으로 변경

- src/main/java/cotato/bookitlist/auth/service/AuthService.java
- src/main/java/cotato/bookitlist/config/RedisConfig.java
- src/main/java/cotato/bookitlist/member/service/MemberService.java
- src/main/java/cotato/bookitlist/post/service/PostService.java
- src/main/java/cotato/bookitlist/review/service/ReviewService.java
- @transactional 을 사용하는 클래스에서 클래스 자체에 적용하는 어노테이션이 @Trancsactional 과 @transactional(readOnly = true) 이 혼재되어 있다. 기본값을 통일한다.
Closes #175
> [Feat] @Transactional 기본값 통일

- README.md
> [Feat] README 작성

- src/main/java/cotato/bookitlist/auth/service/AuthService.java
- src/main/java/cotato/bookitlist/book/controller/BookLikeController.java
- src/main/java/cotato/bookitlist/member/controller/MemberController.java
- src/main/java/cotato/bookitlist/member/domain/Member.java
- src/main/java/cotato/bookitlist/member/repository/MemberRepository.java
- src/main/java/cotato/bookitlist/post/controller/PostController.java
- src/main/java/cotato/bookitlist/post/controller/PostLikeController.java
- src/main/java/cotato/bookitlist/review/controller/ReviewController.java
- src/main/java/cotato/bookitlist/review/controller/ReviewLikeController.java
- src/main/java/cotato/bookitlist/security/CustomAccessDeniedHandler.java
- src/main/java/cotato/bookitlist/security/CustomAuthenticationEntryPoint.java
- src/main/java/cotato/bookitlist/security/SecurityConfig.java
- src/main/java/cotato/bookitlist/security/jwt/AuthDetails.java
- src/main/java/cotato/bookitlist/security/jwt/JwtAuthenticationFilter.java
- src/main/java/cotato/bookitlist/security/jwt/JwtTokenProvider.java
- src/main/java/cotato/bookitlist/security/jwt/dto/AccessTokenInfo.java
- src/main/java/cotato/bookitlist/security/jwt/properties/JwtProperties.java
- src/main/java/cotato/bookitlist/security/oauth/AuthProvider.java
- src/main/java/cotato/bookitlist/security/oauth/KakaoOAuth2User.java
- src/main/java/cotato/bookitlist/security/oauth/NaverOAuth2User.java
- src/main/java/cotato/bookitlist/security/oauth/OAuth2UserInfo.java
- src/main/java/cotato/bookitlist/security/oauth/OAuth2UserInfoFactory.java
- src/main/java/cotato/bookitlist/security/oauth/UserPrincipal.java
- src/main/java/cotato/bookitlist/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
- src/main/java/cotato/bookitlist/security/oauth/service/CustomOAuth2UserService.java
- src/test/java/cotato/bookitlist/factory/WithCustomMockUserFactory.java
- src/test/java/cotato/bookitlist/fixture/MemberFixture.java
> [Feat] 패키지 순환 참조 해결
